host: "127.0.0.1"
port: 8080
log_level: info
auto_reload: false
workers: 1

cors_allowed_origins: ["http://the-other-domain-to-accept.xy"]
cors_allow_credentials: true
cors_allowed_methods: ["*"]
cors_allowed_headers: ["*"]

db_url: mongodb://localhost:27017
db_name: sandbox_requests_db

fastapi_options:
  root_path: "/"
  openapi_url: "/openapi.json"
  docs_url: "/docs"

svc_metadata_url: http://metadata_svc:8080

rabbitmq_host: rabbitmq
rabbitmq_port: 5672
topic_name_download_requested: download_request
topic_name_send_notification: send_notification

data_requester_email: test@example.com
data_requester_name: Data Requester
data_steward_email: test@example.com
data_steward_name: Data Steward
