port: 8010
log_level: debug
auto_reload: true
cors_allowed_origins: ["*"]
cors_allow_credentials: true
cors_allowed_methods: ["*"]
cors_allowed_headers: ["*"]
fastapi_options:
  root_path: "/"
  openapi_url: "/openapi.json"
  docs_url: "/docs"

db_url: mongodb://db:27017
db_name: request

downloadreq_topic_name: download_request
services: {}

rabbitmq_host: = rabbitmq
rabbitmq_port: = 5672

data_requester_email: test@example.com
data_requester_name: Data Requester
data_steward_email: test@example.com
data_steward_name: Data Steward

topic_name_download_requested: download_request
topic_name_send_notification: send_notifications
