port: 8010
log_level: debug
auto_reload: true
db_url: mongodb://db:27017
db_name: request
cors_allowed_origins: ["*"]
cors_allow_credentials: true
cors_allowed_methods: ["*"]
cors_allowed_headers: ["*"]
