#!/bin/bash
# install service in dev container

cd /workspace

# install in edit mode
pip install -e ".[all]"

# load mongodb:
python scripts/populate_request_store.py

# install pre-commit hooks to git:
pre-commit install
